function coords = TrainDataGeneratorBatches(img)
%Image Processing Function
%
% IM      - Input image.
% RESULTS - A scalar structure with the processing results.
%

%--------------------------------------------------------------------------
% Auto-generated by imageBatchProcessor App. 
%
% When used by the App, this function will be called for every input image
% file automatically. IM contains the input image as a matrix. RESULTS is a
% scalar structure containing the results of this processing function.
%
%--------------------------------------------------------------------------



% Replace the sample below with your code----------------------------------
doinput = false;
              
    coords = zeros(2,0);
    fig = figure('KeyPressFcn',@(obj,evt) 0); 
	clf;
    imagesc(img)
    if size(img,3)==1
        colormap(gray)
    end
    axis equal
    hold on
    plot(coords(2,:),coords(1,:),'r*')
    
    while true
       
        if (doinput)
			coord = ginput(1)
            coords = [coords coord(2:-1:1)'];
            doinput = false;
        end
        plot(coords(2,:),coords(1,:),'r*')
		
        drawnow

        
        % step through volume
        while true       

            set(fig,'CurrentCharacter','s');
            waitfor(gcf,'CurrentCharacter');
            k = get(fig,'CurrentCharacter')

            if k == 'x'
                close 
                return;
            elseif double(k) == 8
                disp('Removing')
                coords(:,end) = [];
                hold off
                imagesc(img)
                axis equal
                hold on
                plot(coords(2,:),coords(1,:),'y*')
                break;
            elseif k == ' ' %space
                doinput = true;
                break
            end		
        end

    end


%--------------------------------------------------------------------------
